@echo off

:: 设置Python相关变量
SET PYTHON_PATH=%~dp0wzf\python.exe
SET PYTHONHOME=
SET PYTHONPATH=
SET PYTHONEXECUTABLE=%PYTHON_PATH%
SET PYTHONWEXECUTABLE=%PYTHON_PATH%
SET PYTHON_EXECUTABLE=%PYTHON_PATH%
SET PYTHONW_EXECUTABLE=%PYTHON_PATH%
SET PYTHON_BIN_PATH=%PYTHON_PATH%
SET PYTHON_LIB_PATH=%~dp0wzf\Lib\site-packages

:: 设置FFMPEG路径，使用相对路径
SET FFMPEG_PATH=%~dp0ffmpeg
SET PATH=%FFMPEG_PATH%;%~dp0wzf;%~dp0wzf\Scripts;%PATH%

:: 设置CUDA路径，使用相对路径
SET CUDA_PATH=%~dp0v12.4

:: 运行应用
"%PYTHON_EXECUTABLE%" main.py
pause
