"""
从上游 app/processors/models_data.py 抽取真实 URL/SHA256, 生成 manifest.json
==========================================================================
用法:
  cd D:\\GitHub\\VisoMaster-TRT-Portable
  python\\python.exe _internal\\_gen_manifest.py

输出: 覆盖 _internal/manifest.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# 让上游 models_data 能 import (它内部不依赖 trt 的部分都不强求)
import _internal.bootstrap as bs  # 注入 DLL 路径
bs._register_dll_dirs()

# 上游用相对路径 './model_assets', 我们改成 'models' (扁平, 跟上游一致)
import app.processors.models_data as md

models = md.models_list  # 完整模型列表

# 按上游 model_name 关键字 / 文件名特征分包
# 包顺序: core 必需 / swapper 换脸 / restorer 修复增强 / liveportrait 表情 / extra 其它
def classify(model: dict) -> str:
    name = model.get("model_name", "")
    path = model.get("local_path", "").lower()
    n = name.lower()

    # core - 启动必需的最小集 (检测+1个换脸+1个修复+arcface+常用关键点+遮挡)
    core_keys = (
        "RetinaFace", "Inswapper128", "GFPGANv1.4", "ArcFace",
        "FaceLandmark106", "FaceLandmark68", "Occluder", "FaceParser",
    )
    if any(k.lower() in n.lower() for k in core_keys) and "Inswapper128ArcFace" not in name:
        return "core"
    if name == "Inswapper128ArcFace":
        return "core"

    # liveportrait
    if "liveportrait" in n or "liveportrait" in path:
        return "liveportrait"

    # swapper
    if any(k in n for k in ("Swapper", "Swap", "Ghost", "CSCS", "SimSwap", "InStyle")):
        return "swapper"

    # restorer / enhancer
    if any(k in n for k in ("GFPGAN", "GPEN", "Codeformer", "CodeFormer", "VQFR",
                            "RestoreFormer", "RealEsr", "ESRGAN", "BSRGAN",
                            "Ultra", "Enhance")):
        return "restorer"

    return "extra"


packs: dict[str, list[dict]] = {
    "core": [], "swapper": [], "restorer": [],
    "liveportrait": [], "extra": [],
}

for m in models:
    url = m.get("url")
    if not url:
        # liveportrait trt 文件没 url (build 出来的), 跳过下载, 但保留 onnx 来源
        continue
    local = m["local_path"]
    # 跟上游完全一致: model_assets/xxx
    rel = local.replace("./model_assets/", "model_assets/")
    rel = rel.replace("\\", "/")
    pack = classify(m)
    packs[pack].append({
        "name": m.get("model_name", Path(rel).stem),
        "path": rel,
        "sha256": m.get("hash"),
        "url": url,
    })

# 算每包总大小 (URL 没有 size 信息, 留空让 download_with_resume 自己拿 Content-Length)
manifest = {
    "version": "1.0.0",
    "_comment": "auto-generated by _gen_manifest.py from upstream models_data.py",
    "packs_meta": {
        "core":         {"desc": "Core required (detector + Inswapper + GFPGAN + arcface)",
                         "size_mb": 0},
        "swapper":      {"desc": "All face swappers (GhostFace / SimSwap / InStyle / CSCS)",
                         "size_mb": 0},
        "restorer":     {"desc": "Restorers and enhancers (GFPGAN / CodeFormer / GPEN / ESRGAN)",
                         "size_mb": 0},
        "liveportrait": {"desc": "LivePortrait expression driving (6 onnx)",
                         "size_mb": 0},
        "extra":        {"desc": "Other (parsing / colorizer / extra detectors)",
                         "size_mb": 0},
    },
    "packs": {},
}
for pack, items in packs.items():
    # 把每个 item 改写为 mirrors 数组 (主+备), 兼容下载器
    out = []
    for it in items:
        github_url = it["url"]
        # huggingface 镜像猜测: hf 上有 visomaster/visomaster-assets 的同名文件?
        # 没把握, 这里就只配 github 一个源 (官方源就够了, github 在国内挂代理可下)
        out.append({
            "path": it["path"],
            "sha256": it["sha256"],
            "size_mb": 0,
            "mirrors": [github_url],
        })
    manifest["packs"][pack] = out

out_path = ROOT / "_internal" / "manifest.json"
out_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

# 打印统计
total = sum(len(v) for v in packs.values())
print(f"\nGenerated manifest with {total} models:")
for pack, items in packs.items():
    print(f"  {pack:<14} {len(items):>3} files")
print(f"\nOutput: {out_path}")
